# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages
RUN pip install --trusted-host -r requirements.txt

# Run the command to start the Flask app
CMD ["python", "app.py"]
