# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /

# Install dependencies
COPY requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY . /
